openapi: 3.1.0
info:
  title: Geocoding and Reverse Geocoding API
  version: 1.0.0
servers:
  - url: https://host/{version}/GIS_BB/Geocoding_ReverseGeocoding
    variables:
      version:
        description: API version
        default: v1
paths:
  /geocode:
    post:
      summary: Geocode an Address
      description: Geocode an address to obtain geographic coordinates.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressData'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request

  /reverse-geocode:
    post:
      summary: Reverse Geocode Coordinates
      description: Reverse geocode geographic coordinates to obtain an address.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coordinates'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request

  /batch-geocode:
    post:
      summary: Batch Geocode
      description: Perform batch geocoding or reverse geocoding using a table file with multiple addresses or coordinates.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeocodingBatch'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request

  /geocode-result/{resultId}:
    get:
      summary: Retrieve Geocode Result by ID
      description: Retrieve the geocoding result for a specific ID.
      parameters:
        - name: resultId
          in: path
          description: ID of the geocoding result to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Not Found

  /reverse-geocode-result/{resultId}:
    get:
      summary: Retrieve Reverse Geocode Result by ID
      description: Retrieve the reverse geocoding result for a specific ID.
      parameters:
        - name: resultId
          in: path
          description: ID of the reverse geocoding result to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Not Found

components:
  schemas:
    AddressData:
      type: object
      properties:
        Address:
          type: string
        Longitude:
          type: number
          format: double
        Latitude:
          type: number
          format: double

    Coordinates:
      type: object
      properties:
        Longitude:
          type: number
          format: double
        Latitude:
          type: number
          format: double

    GeocodingBatch:
      type: object
      properties:
        BatchType:
          type: string
        BatchName:
          type: string
        Status:
          type: string
        TimeStamp:
          type: string
          format: date-time