openapi: 3.1.0
info:
  title: Geofencing API
  version: 1.0.0
servers:
  - url: https://host/{version}/GIS_BB/Geofencing
    variables:
      version:
        description: API version
        default: v1
paths:
  /geofences:
    get:
      summary: List Geofences
      responses:
        '200':
          description: Successful response with a list of geofences
    post:
      summary: Create Geofence
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Geofence'
      responses:
        '201':
          description: Successful response after creating geofence

  /geofences/{geofenceId}:
    get:
      summary: Get Geofence by ID
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with geofence details
        '404':
          description: Geofence not found
    put:
      summary: Update Geofence
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Geofence'
      responses:
        '204':
          description: Successful response after updating geofence
        '404':
          description: Geofence not found
    delete:
      summary: Delete Geofence
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response after deleting geofence
        '404':
          description: Geofence not found

  /geofences/{geofenceId}/status:
    get:
      summary: Get Geofence Status
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with geofence status
        '404':
          description: Geofence not found

  /geofences/{geofenceId}/activate:
    post:
      summary: Activate Geofence
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response after activating geofence
        '404':
          description: Geofence not found

  /geofences/{geofenceId}/deactivate:
    post:
      summary: Deactivate Geofence
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response after deactivating geofence
        '404':
          description: Geofence not found

  /geofences/{geofenceId}/elements:
    get:
      summary: List Geofence Elements
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with a list of geofence elements
        '404':
          description: Geofence not found
    post:
      summary: Add Geofence Element
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeofenceElement'
      responses:
        '201':
          description: Successful response after adding geofence element
        '404':
          description: Geofence not found

  /geofences/{geofenceId}/elements/{elementId}:
    delete:
      summary: Remove Geofence Element
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
        - name: elementId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response after removing geofence element
        '404':
          description: Geofence or element not found

  /geofences/{geofenceId}/rules:
    post:
      summary: Create Action Rule for Geofence
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRule'
      responses:
        '201':
          description: Successful response after creating action rule
        '404':
          description: Geofence not found

  /geofences/{geofenceId}/elements/{elementId}/actions:
    post:
      summary: Create Element Action Rule for Geofence
      parameters:
        - name: geofenceId
          in: path
          required: true
          schema:
            type: string
        - name: elementId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeofenceNotification'
      responses:
        '201':
          description: Successful response after creating element action rule
        '404':
          description: Geofence or element not found

components:
  schemas:
    Geofence:
      type: object
      properties:
        Name:
          type: string
        Shape:
          type: string
        Size:
          type: number
          format: double
        Status:
          type: boolean
    GeofenceElement:
      type: object
      properties:
        ElementType:
          type: string
        TrackingMethod:
          type: string
    ActionRule:
      type: object
      properties:
        ActionType:
          type: string
        Action:
          type: string
    GeofenceNotification:
      type: object
      properties:
        NotificationType:
          type: string
        Recipient:
          type: string
        RecipientType:
          type: string