openapi: 3.1.0
info:
  title: Spatial Awareness and Analysis API
  version: 1.0.0
servers:
  - url: https://host/{version}/gisBB/spatialAwarenessAnalysis
    variables:
      version:
        description: API version
        default: v1
paths:
  /metadata:
    get:
      summary: Get Metadata
      description: Retrieve metadata that describes the purpose and functionality of geospatial analysis tasks or processes.
      responses:
        '200':
          description: Successful response with metadata
        '400':
          description: Bad Request

  /processes:
    get:
      summary: Get Available Processes
      description: Retrieve detailed information that describes the processes that can be run on the service.
      responses:
        '200':
          description: Successful response with available processes
        '400':
          description: Bad Request

  /executeTask:
    post:
      summary: Execute Geoprocessing Task
      description: Execute a geoprocessing task to perform basic spatial analysis operations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/geoprocessing'
      responses:
        '200':
          description: Successful response with geoprocessing result
        '400':
          description: Bad Request

  /taskStatus/{taskId}:
    get:
      summary: Get Task Status
      description: Get the status of an asynchronously executed geoprocessing task.
      parameters:
        - name: taskId
          in: path
          description: ID of the geoprocessing task
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with task status
        '404':
          description: Task not found

  /taskResult/{taskId}:
    get:
      summary: Get Task Result
      description: Get the result of a finished geoprocessing task.
      parameters:
        - name: taskId
          in: path
          description: ID of the geoprocessing task
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with task result
        '404':
          description: Task not found

  /terminateTask/{taskId}:
    post:
      summary: Terminate Task
      description: Terminate an asynchronously executed geoprocessing task.
      parameters:
        - name: taskId
          in: path
          description: ID of the geoprocessing task
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task termination request received
        '404':
          description: Task not found

components:
  schemas:
    geoprocessing:
      type: object
      properties:
        processingName:
          type: string
        description:
          type: string
        parameters:
          type: array
          items:
            type: object
            properties:
              parameterName:
                type: string
              value:
                $ref: '#/components/schemas/parameterString'  # Use the appropriate parameter data type schema
              code:
                type: string
              defaultValue:
                $ref: '#/components/schemas/parameterString'  # Use the appropriate parameter data type schema

    executionStatus:
      type: object
      properties:
        status:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        result:
          type: object

    parameterString:
      type: string
    parameterNumber:
      type: number
      format: double
    parameterInteger:
      type: integer
    parameterBoolean:
      type: boolean
    parameterArray:
      type: array
      items:
        type: string
    parameterObject:
      type: object
      properties:
        key1:
          type: string
        key2:
          type: number
